#include <stdlib.h>
#include <stdio.h>
#include <gtk/gtk.h>
#include <winsock.h>
#include <MYSQL/mysql.h>
#include <string.h>
#include "index.h"
#include "Inscription.h"
#include "connexion.h"
#include "insertion.h"
